import {
  Entity,
  PrimaryColumn,
  Column,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { Post } from './post.entity';
import { User } from '../../users/entities/user.entity';

/**
 * feed_items — denormalized per-user timeline row.
 *
 * When a post is created, FeedService fans it out to a row in this table
 * for each of the author's friends. Reading the feed becomes a simple
 * single-table keyset scan on (viewer_id, post_created_at DESC, post_id DESC)
 * instead of the old pattern:
 *
 *   1. SELECT friend IDs from friendships
 *   2. SELECT posts WHERE author_id IN (...) ORDER BY created_at OFFSET n
 *
 * That old pattern is O(n) on friendships x posts and cannot use a covering
 * index efficiently at 1M+ rows.
 *
 * ── Composite Primary Key ───────────────────────────────────────────────
 * This table is RANGE-partitioned on created_at (see Migration 036).
 * PostgreSQL requires every PRIMARY KEY / UNIQUE constraint on a partitioned
 * table to include the partition key column. Therefore the PK is
 * (id, created_at) rather than just (id).
 *
 * The global UNIQUE (viewer_id, post_id) constraint is dropped — it cannot
 * span partitions without including created_at, which changes semantics.
 * Deduplication is enforced at the application layer via ON CONFLICT DO NOTHING
 * in FeedService.fanOut().
 *
 * ── Fan-out limits ──────────────────────────────────────────────────────
 * At 1M users, a highly-connected user (e.g. 5 000 friends) posting once
 * inserts 5 000 rows. For a typical social graph (avg 100–200 friends) this
 * is ~200 rows/post — completely fine. If a "celebrity" user with tens of
 * thousands of connections posts, fan-out can be moved to a background
 * BullMQ job to avoid a slow write path (future TODO behind a feature flag).
 *
 * ── Partitioning ────────────────────────────────────────────────────────
 * Monthly partitions are managed by PartmanService (cron: 1st of month at 00:05 UTC).
 * A DEFAULT overflow partition catches any rows until the next cron run.
 * Manual trigger: POST /v1/admin/ops/partman/run
 */
@Entity('feed_items')
@Index('ix_feed_items_viewer_timeline', ['viewerId', 'postCreatedAt', 'postId'])
@Index('ix_feed_items_viewer_author', ['viewerId', 'authorId'])
export class FeedItem {
  /**
   * Surrogate UUID — generated by PostgreSQL (gen_random_uuid()).
   * Part of composite PK (id, created_at) to satisfy the partitioning rule.
   */
  @PrimaryColumn({ type: 'uuid', default: () => 'gen_random_uuid()' })
  id!: string;

  /** The user whose feed this row appears in. */
  @Column({ name: 'viewer_id', type: 'uuid' })
  viewerId!: string;

  /** The post being surfaced. */
  @Column({ name: 'post_id', type: 'uuid' })
  postId!: string;

  /** Denormalized for fast fan-out pruning on unfollow / unfriend. */
  @Column({ name: 'author_id', type: 'uuid' })
  authorId!: string;

  /**
   * Denormalized sort key — matches the post's created_at at fan-out time.
   * Stored so the timeline query never touches social_posts for ordering;
   * posts are joined only to hydrate the payload.
   */
  @Column({ name: 'post_created_at', type: 'timestamptz' })
  postCreatedAt!: Date;

  /**
   * Row creation timestamp — also the PARTITION KEY.
   * Part of composite PK (id, created_at).
   * Defaults to NOW() at INSERT time.
   */
  @PrimaryColumn({
    name: 'created_at',
    type: 'timestamptz',
    default: () => 'NOW()',
  })
  createdAt!: Date;

  @ManyToOne(() => Post, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'post_id' })
  post!: Post;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'viewer_id' })
  viewer!: User;
}
